### ISSUE TITLE
backslashbox entries are swapped

### ISSUE THREAD

**Issue by toerb** [JDMCreator/LaTeXTableEditor#10]
Hi,

this is regarding the "divided" cell effect.
**Display on web page**
![backslashbox_web](https://user-images.githubusercontent.com/2090409/53255853-cea73580-36c6-11e9-9c58-42d6c31776cd.png)

**Generated LaTeX output**
```
\begin{table}
\centering
\begin{tabular}{l}
\backslashbox{{[}TEXT OVER]}{{[}TEXT UNDER]} 
\end{tabular}
\end{table}
```
**Compiled LaTeX result**
![backslashbox_latex](https://user-images.githubusercontent.com/2090409/53255852-ce0e9f00-36c6-11e9-884e-a1211525689b.png)

So from my point of view the first and the second parameters for backslashbox have to be swapped.

Best regards
toerb

**Comment by JDMCreator** [comment]
I confirmed this bug. Thank you for your report. I'll fix this issue as soon as I can.

For future references, this bug has a high priority because it is related to the LaTeX output.

**Comment by JDMCreator** [comment]
I fixed the issue and implemented a way to change the color of the diagonal line. Also, I changed the way placeholder texts for those cells were handled.
