### ISSUE TITLE
Multiple rows + textbf are clashing

### ISSUE THREAD

**Issue by Loewe1000** [JDMCreator/LaTeXTableEditor#15]
If you make a font bold and use multiple rows in one cell there is an error, because you can't use a newline \\ inside of a \textbf

So this code is generated:
\multirow{3}{*}{\begin{tabular}[c]{@{}l@{}}\textbf{ fachspez.\\Selbstkonzept }\end{tabular}} 

You may need to edit the algorithm so that it will use one \textbf for each line.
Apart from that error, the tool is awesome!

**Comment by JDMCreator** [comment]
Wow, nice catch ! I'm surprised I didn't realize it before. I'll fix it right away.

**Comment by JDMCreator** [comment]
Sorry for the late update. I fixed the issue, which happened also with `\textit`, `\color` and `\uline` commands.
