### ISSUE TITLE
Refreshing Table is bringing some unnecessary symbol

### ISSUE THREAD

**Issue by karimmd** [JDMCreator/LaTeXTableEditor#16]
While I refresh my latex table there is always this sign "<><>" for every line in the table. Previously, I did not have this issue. 
![Screenshot_20191214_040936](https://user-images.githubusercontent.com/6984392/70829150-e30c1880-1e27-11ea-9edf-35212aea3ebd.png)

**Comment by JDMCreator** [comment]
What a strange issue ! This is new and I think it is due to some changes in the way browsers treats lines and a special tag (`<wbr>`) that I used to avoid some issues with newlines.
