### ISSUE TITLE
extend from generation to editing

### ISSUE THREAD

**Issue by lukasc-ch** [JDMCreator/LaTeXTableEditor#2]
Right now the table generator is a one-way street: I can write the table and generate LaTeX. But maybe one day later I want to edit my table, so I have the LaTeX code, want to use the editor, and generate new LaTeX code with the changes. I think this is a common scenario, so adding a LaTeX to table parser would make a great addition to this project.

**Comment by JDMCreator** [comment]
Hi Lukas, this feature has already been implemented since the first version. To use it, click on "New table" (first button in the toolbar) and then "Import a LaTeX table". Let me know if it meets your expectations or if I should move this feature somewhere else.
