### ISSUE TITLE
Generates a lot of unnecessary \texcolor[rgb] entries, which makes the code un-readable

### ISSUE THREAD

**Issue by MichaelKaip** [JDMCreator/LaTeXTableEditor#20]
Here's an example:
`\begin{longtabu}{lll}
\caption{Beschreibung der funktionalen Anforderungen und Priorisierung\label{Tabelle 2}}\\ \hline
\begin{tabular}[c]{@{}l@{}}\\\textbf{Nr.}\end{tabular} & \begin{tabular}[c]{@{}l@{}}\\\textbf{Beschreibung}\end{tabular} & \begin{tabular}[c]{@{}l@{}}\\\textbf{Priorität}\end{tabular} \endfirsthead \hline
FA 1.0 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Dem Auftragnehmer wird ein bereits bestehendes Drohnen-Simulationsprojekt }\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{zur Verfügung~gestellt. Diese Entwicklung wurde mit AirSim begonnen, jedoch }}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{nicht fertig gestellt, da eine Schwarmflug-Simulation mit der zur Verfügung~}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{stehenden Hardware nicht umgesetzt werden konnte. Im Rahmen der vorliegen-}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{den }}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Anforderungsdefinition soll eine Schwarmflug-Simulation umgesetzt werden }}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{und }}}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{es ist in diesem Zusammenhang zu prüfen, inwieweit dies auf der Grundlage }}}}}}}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{der }}}}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{bereits bestehenden Implementierung realisiert werden kann, oder ob es }}}}}}}}}}}}}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{notwendig }}}}}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{ist das Projekt neu aufzusetzen.}}}}}}}}}}}}}}}}}}}}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}\end{tabular} & hoch \\ \hline
FA 2.0 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Die für die Entwicklung vorgesehene Programmiersprache ist C++.}\\\textcolor[rgb]{0.2,0.2,0.2}{}\end{tabular} & hoch \\ \hline
FA 3.0 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Die Software auf verschiedenen lauffähig sein, also }\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{plattformunabhängig }}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{implementiert werden.}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}\end{tabular} & mittel \\ \hline
FA 4.0 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Die Simulationslogik soll sinnvoll auf verschiedene Komponenten aufgeteilt und }\\\textcolor[rgb]{0.2,0.2,0.2}{über }\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{wohldefinierte Schnittstellen miteinander verbunden werden. Z.B. Umge-}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{bung (Raum), }}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Umgebungsbedingungen, Flugobjekt. Dadurch soll sichergestellt }}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{werden, dass die}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Simulationssoftware dahingehend erweiterbar ist, das bspw. }}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{verschiedene Flugobjekte }}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{(Quadrocopter, Hexacopter, Hubschrauber, etc.) }}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{implementiert und simuliert werden }}}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{können.}}}}}}}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}}}}}}}}}}}}}}}}}}}\end{tabular} & hoch \\ \hline
FA 4.1 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Als Minimalanforderung für Version 1.0 wird ein Flugobjekt (z.B. Quadrocopter), }\\\textcolor[rgb]{0.2,0.2,0.2}{eine }\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Umgebung sowie die Möglichkeit einen Schwarmflug mit mehr als 3 }}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Flugobjekten }}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{derselben Art zu simulieren.}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}}}}\end{tabular} & hoch \\ \hline
FA 4.2 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Des Weiteren ist es erforderlich, dass eine Möglichst reale Simulationsumge-}\\\textcolor[rgb]{0.2,0.2,0.2}{bung }\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{(z.B. Natur und/oder Stadtgebiet, etc.) zur Verfügung steht.}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}\end{tabular} & hoch \\ \hline
FA 5.0 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Die Software soll über eine Nutzeroberfläche bedienbar sein, an die folgende }\\\textcolor[rgb]{0.2,0.2,0.2}{Anforderun}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{gen gestellt werden:}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}\end{tabular} &  \\ \hline
FA 5.1 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Dem Nutzer soll es möglich sein, vor dem Start einer Schwarmflug-Simulation }\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{verschiedene Simulationsparameter einzustellen,~~wie bspw. Anzahl und Art }}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{der }}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Flugobjekte (Quadrocopter, Hexacopter, etc.), Umgebungsparameter }}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{(Sonne, }}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Regen, starker Wind, etc.), etc. Für Version 1.0 kommt es dabei }}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{weniger darauf an, }}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{das möglichst viele unterschiedliche~~Parameter einstellbar }}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{sind als vielmehr darauf, }}}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{dass entsprechende Einstellmöglichkeiten und die }}}}}}}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Schnittstellen zur Erweiterbarkeit }}}}}}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{der Software gegeben sind.}}}}}}}}}}}}}}}}}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}}}}}}}}}}}}}}}}}}}}}}}}}}\end{tabular} & hoch \\ \hline
FA 5.2 & \begin{tabular}[c]{@{}l@{}}\\Als Framework für die Entwicklung der Nutzeroberfläche wäre das Qt-Framework \\wünschenswert.\\\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}\end{tabular} & mittel \\ \hline
FA 5.3 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Es sollen Informationen über die in einer Simulation verwendeten Flugob-}\\\textcolor[rgb]{0.2,0.2,0.2}{jekte }\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{(z.B. Modell, Batteriekapazität und Füllstand, Entfernung bis zur naech-}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{sten }}\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{Service-Station, Flughoehe, Fluggeschwindigkeit, etc.) angezeigt }}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{werden.}}}}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}}}}\end{tabular} & mittel \\ \hline
FA 6.0 & \begin{tabular}[c]{@{}l@{}}\textcolor[rgb]{0.2,0.2,0.2}{}\\\textcolor[rgb]{0.2,0.2,0.2}{Die Implementierung der Simulationslogik soll unter Verwendung von AirSim }\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{(Aerial Informatics and Robotics Simulation) erfolgen.}}}\\\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{\textcolor[rgb]{0.2,0.2,0.2}{}}}\end{tabular} & hoch \\ \hline
\end{longtabu}
`

**Comment by MichaelKaip** [comment]
Is there a possibility to avoid this?

**Comment by JDMCreator** [comment]
Hi @MichaelKaip,

This is absolutely a bug and I will try to fix it. To help me, could you send me the JSON code associated with your table ? To do so, use the menu `File > Generate JSON`.

**Comment by JDMCreator** [comment]
The issue has been mostly fixed and the website will be updated in a few minutes. However, empty `\textcolor` could not be removed because this may cause fatal errors in some rare cases and I prefer "ugly" code than a code that won't compile. I will have to think of a solution for this.

However, duplicated `\textcolor` should not appear anymore.
