### ISSUE TITLE
Likely not an issue - but a question: How to do table in-line? 

### ISSUE THREAD

**Issue by Kingpatzer** [JDMCreator/LaTeXTableEditor#22]
The generator produces a float environment that gets pushed to the back material. 

How do I keep a rotated table in-line in the final document?

**Comment by davidfarmer** [comment]
I like to use the \FloatBarrier macro from the "placeins" package.

**Comment by JDMCreator** [comment]
Click on the `Output` menu, then click on `Settings`. Uncheck `Use table as a float`

Rotated tables without a float environment are not supported yet. I could definitively work on this. You can use the `adjustbox` package using something like this : 

```latex
%\usepackage{adjustbox}
\begin{adjustbox}{angle=90}
% The code of your table here
\end{adjustbox}
```

**Comment by JDMCreator** [comment]
Rotated tables without a float environment is supported since version 2.0.
