### ISSUE TITLE
Not able to change font color

### ISSUE THREAD

**Issue by suryadevs** [JDMCreator/LaTeXTableEditor#25]
Clicking on any color in font color doesn't change it. Only the default red color gets applied

**Comment by JDMCreator** [comment]
Confirmed.

Bug informations after debugging : This is an issue specific to non-Firefox browsers as I used a mozilla-specific property (`Event.originalEvent` instead of `Event.srcElement`).

This issue should be fixed today. Thank you for reporting this issue.
