### ISSUE TITLE
Is there a way to disable automatic escaping of LaTeX syntax?

### ISSUE THREAD

**Issue by dniku** [JDMCreator/LaTeXTableEditor#28]
I haven't found an option to do so in the interface, and without that option it is very annoying to have to use the "$" button in the toolbar all the time and to clean up `\textbackslash` in the resulting code.

**Comment by JDMCreator** [comment]
I understand it is annoying. There is no option available to allow you to write LaTeX code directly. There's several issues that are related to allowing this (mostly about the way to handle formatting). It would be a massive update to the core code behind the generator. However, I'll keep this in mind as it would definitively be very useful to a lot of people and be way more user-friendly.

**Comment by JDMCreator** [comment]
I'm working on this issue and this should be fixed in the next release.
