### ISSUE TITLE
Issue when importing dollar symbols

### ISSUE THREAD

**Issue by nsfinch** [JDMCreator/LaTeXTableEditor#33]
Hello,

I typically save each table I create in separate *.tex files.  When I need to update these tables, I reimport from the the tex files to your editor (offline mode -- many thanks for making this available) and have noticed parsing problems.  

Specifically, I have financial data formatted $1,234K for example.  When importing into the table creator, the parser misses the leading digit of numbers formatted this way.  I've attached two images that display the original table and the same data re-imported into the table editor.

Once again, thanks for making this tool available and let me know if you need any additional data points or test cases.

Best regards,
Nolan

Clean Table Example:  
![Import_Error_Example--CleanTable](https://user-images.githubusercontent.com/17561415/106057668-890ef680-60ad-11eb-9f1b-73276cc1f7e3.png)

Same Table Re-imported into Editor:
![Import_Error_Example--ReImportedError](https://user-images.githubusercontent.com/17561415/106057706-92985e80-60ad-11eb-9789-c6ffcd480ea6.png)

**Comment by JDMCreator** [comment]
Thank you for your kind words. Could you post here the LaTeX code you are trying to import ?

**Comment by JDMCreator** [comment]
Never mind, I could reproduce the issue. I'll look into it.

**Comment by JDMCreator** [comment]
Issue fixed in last release.

**Comment by nsfinch** [comment]
Excellent - thanks for the quick turnaround on this issue.  Cheers.
