### ISSUE TITLE
PreTeXt updates: titles and header rows

### ISSUE THREAD

**Issue by rbeezer** [JDMCreator/LaTeXTableEditor#35]
Thanks for your support of PreTeXt as an output format.  We've switched so that tables now have a "title" element (as per Chicago Manual of Style), and no longer have a "caption" element.  It would be authored **before** the actual content inside the "tabular" element.

We have also added support for marking rows as header rows.  They must be consecutive, and must be at the beginning.  Markup looks like:

```xml
<row header="yes">
```

and we also allow the contents of a header row to be written vertically, that'd be

```xml
<row header="vertical">
```

`"no"` is the default, so is not necessary to specify.

Thanks!

**Comment by JDMCreator** [comment]
It's always great to hear news from the PreTeXt project! The website was updated to reflect the update on titles.

Of course, I would strongly advise against breaking changes as it makes it harder to build 3rd-party tools to support PreTeXt.

The website doesn't have any way to assign "roles" to rows, cells or columns yet. However, I take note of the changes in your specs.

**Comment by rbeezer** [comment]
Thanks for this too.  We still have rolling releases and do make changes, but usually preserve backward-compatibility, along with warnings.  So nobodygets bit too hard when something like this lags a bit.  In fact, this rep[ort was due to an author who got a warning from PreTeXt.
