### ISSUE TITLE
Special characters in PreTeXt output

### ISSUE THREAD

**Issue by rbeezer** [JDMCreator/LaTeXTableEditor#36]
A report from an author with some stray characters in tables.

`&nbsp;` is HTML and is not recognized in an XML document unless specifically defined.  So it should not appear at all.  `<nbsp/>` is the PreTeXt equivalent, but should only be necessary every once in a while.

Same report mentions Unicode `U+200B`.  We're not entirely certain where this might have come from.

Original report:

https://groups.google.com/g/pretext-support/c/claAXX7snII/m/We5SKf6OBQAJ

**Comment by JDMCreator** [comment]
The issues were fixed in the last releases. Zero-width space characters (`U+200B`) are added by the editor to make it possible for all browsers to edit mathemical expressions. I forgot to remove them in the generated code for PreTeXt.

**Comment by rbeezer** [comment]
Thanks!
