### ISSUE TITLE
Indentation for PreTeXt output

### ISSUE THREAD

**Issue by rbeezer** [JDMCreator/LaTeXTableEditor#4]
I see that indentation style can be adjusted.  Our standard for source is no-tabs and two spaces per indentation level.  Is it possible to make that the default behavior for PreTeXt output?  Thanks.

**Comment by JDMCreator** [comment]
Hi, no trouble to make two spaces the default behavior for PreTeXt output. Is no-tabs a standard or a requirement for PreTeXt ?

**Comment by davidfarmer** [comment]
no-tabs is not a technical requirement, but there is no reason to use any tabs

We are not yet to the point of agreeing on a "standard".  More precisely, there
will not be any standard.  But for authors who expect others to collaborate,
there are strong suggestions with a few choices left to individual taste.
