### ISSUE TITLE
Incompatibility between vcell and calc

### ISSUE THREAD

**Issue by fpantigny** [JDMCreator/LaTeXTableEditor#43]
There seems to be an incompatibility between the package `vcell`  (2020/05/16 v1.0.1) and the package `calc` (2017/05/25 v4.3). 

Here is a MWE.

```
\documentclass{article}
\usepackage{vcell,calc}

\begin{document}
\begin{tabular}{lll} 
\vcell{C} & \vcell{\rule{1pt}{3cm}} \\[-\rowheight]
\printcellmiddle & \printcelltop \\
N & P \\
\end{tabular}
\end{document}
```

The output is not as expected.
[essai.pdf](https://github.com/JDMCreator/LaTeXTableEditor/files/6321140/essai.pdf)

**Comment by JDMCreator** [comment]
I'll look into this, but I'll probably have to update `vcell`.

**Comment by JDMCreator** [comment]
I fixed the issue and I uploaded an update to `vcell`. I'm waiting for CTAN to accept the update.

**Comment by fpantigny** [comment]
Perfect.
