### ISSUE TITLE
Fail to generate text contents inside cells 

### ISSUE THREAD

**Issue by li-xin-yi** [JDMCreator/LaTeXTableEditor#44]
I edit it with Chrome, no matter type text directly in cell or modify the `LaTeX Content` in the right panel `Cell properties`, the contents are always missing in the final generated LaTeX codes.

![image](https://user-images.githubusercontent.com/10118462/115340052-06f61180-a174-11eb-85a6-5b269cb68816.png)

**Comment by felixkeller98** [comment]
I had the same Problem. Try to open your Tab in an incognito window. This fixed it for me. 
A browser extension might be blocking it somehow. 
Hope this helps.
