### ISSUE TITLE
Multiple cell selection without using the mouse

### ISSUE THREAD

**Issue by sirreyson** [JDMCreator/LaTeXTableEditor#52]
While trying to merge cells, CTRL + Arrow key / CTRL + Shift + Arrow key / CTRL + Multiple cell selection (holding left click and dragging) won't work/properly select the cells I wish to Merge, I have to manually hold CTRL and click each cell individually for the table editor to recognize I'm selecting multiple cells to merge them.

It gets tedious then you have to merge multiple cells because your source files don't merge cells properly before importing.
![suggestion](https://user-images.githubusercontent.com/44481074/141024799-33e6ca91-4b0c-4dce-af94-8d353f1f7846.png)

**Comment by JDMCreator** [comment]
Duly noted.

>  your source files don't merge cells properly before importing

Could you explain what you mean?

**Comment by sirreyson** [comment]
> Could you explain what you mean?
Oh my bad. I didn't mean merged cells unmerged when loading from Excel or importing them from LaTeX.
I was just trying to give like a specific case in which, for X o Y reason, I couldn't merge these cells on Excel and I had to merge them on the Table Editor
