### ISSUE TITLE
Rectangular cells selection with SHIFT 

### ISSUE THREAD

**Issue by fredlefred** [JDMCreator/LaTeXTableEditor#53]
The following patch enable rectangular select with SHIFT, which is a more natural way of selecting cells in a table.

[shift-cell-select.js.js.diff.txt](https://github.com/JDMCreator/LaTeXTableEditor/files/7576059/shift-cell-select.js.js.diff.txt)

**Comment by fredlefred** [comment]
the first version doesn't work with splitted cells, this ones fix it.

[shift-cell-select.js.js.diff.txt](https://github.com/JDMCreator/LaTeXTableEditor/files/7583331/shift-cell-select.js.js.diff.txt)

**Comment by JDMCreator** [comment]
Thank you for your suggestion, I will look into it. I have to completely rewrite the way I handle selection, to fix #52. Hopefully, this can be fixed at the beginning of 2022.
