### ISSUE TITLE
[Request] Decimal separator selector

### ISSUE THREAD

**Issue by Skoobs23** [JDMCreator/LaTeXTableEditor#54]
Greetings, JDMCreator, how are you?

Here in Brazil we show decimal numbers separated by a comma and not a dot. For example, the number 1,234.5 in North America/Europe is shown here like this: 1.234,5 or 1234,5. Every time I import an excel table into latex-tables it turns all the comma separators into dots and I need to find and replace them in Word. It would be great to have a feature to change the decimal separators so that when I import the tables, they are the right way for me.

Anyway, thanks for the website.

Cheers,

**Comment by JDMCreator** [comment]
Hi, the next version will feature major improvements to the way the editor handle numbers, including selecting the decimal separator. It should be released in January 2022.
