### ISSUE TITLE
[Feature Request] Support for tabularray package

### ISSUE THREAD

**Issue by leoleoasd** [JDMCreator/LaTeXTableEditor#56]
`tabularray` is a modern, actively-maintained table package based on LaTeX3. **It is a new package, and it isn't included in TeX Live 2021**. It has a modern interface, supports all features like diabox / booktabs / tabu-like X columns / multirow / multicolumn, and **there are no bugs and conflicts when using these features simultaneously.**

---

Here are some key feature examples extracted from their manual:

tabu column:
![image](https://user-images.githubusercontent.com/37735580/149052795-dd94f690-0476-4e94-a4c2-bc926ef9f332.png)

in-cell line wrapping and alignment:

![image](https://user-images.githubusercontent.com/37735580/149053160-027563ca-899e-47ad-9414-904547b173b9.png)

easily multicell and multirow:
![image](https://user-images.githubusercontent.com/37735580/149052857-acddd366-79e3-4b55-8368-f27d0e309f09.png)

hlines and vlines:
![image](https://user-images.githubusercontent.com/37735580/149052819-83d8e601-7fcb-4123-8200-616a76bf4984.png)

And their new interfaces:

![image](https://user-images.githubusercontent.com/37735580/149052986-75ac13d8-a836-4cfe-a8df-cf0360685477.png)

![image](https://user-images.githubusercontent.com/37735580/149053010-beade85f-312a-4afb-8e34-f1f7987519b0.png)

---

Current implementation using tabular or tabularx combined with multirow have trouble aligning items. For example, when I export the following table to latex, some cells aren't center-aligned.

![image](https://user-images.githubusercontent.com/37735580/149052716-9ddb5a5d-eef2-4f29-8516-d5d306fbee5d.png)

When I switch to tabularray, all my alignment and spacing problems got fixed immediately.

For more info, see: https://ctan.org/pkg/tabularray

**Comment by JDMCreator** [comment]
Exporting `tabularray` tables is expected to be supported before summer 2022. You can follow the progress on [this discussion](https://github.com/JDMCreator/LaTeXTableEditor/discussions/49). The first step is to support importing `tabularray` tables as it is important that every table exported by the editor can be edited after. You can already do so for most of the features. However, borders are not supported yet.
