### ISSUE TITLE
Insert row / delete row 

### ISSUE THREAD

**Issue by Charuka2370** [JDMCreator/LaTeXTableEditor#63]
This function does not work properly

**Comment by dthuremella** [comment]
can't insert a  full column next to a colum that starts with a multirow

**Comment by dthuremella** [comment]
When I have a header row where where columns are merged for that row and I
try to add another column, it automatically merges the top row of that
column as well, which is not what I want.

**Comment by JDMCreator** [comment]
This is intended behaviour.
