### ISSUE TITLE
Disable longtable?

### ISSUE THREAD

**Issue by Warborn123** [JDMCreator/LaTeXTableEditor#67]
Hi, it will be great if there is a switch for enabling longtable. Longtable will have some weird issue when using MNRAS style of LaTeX. Thanks.

**Comment by JDMCreator** [comment]
Hi, I'm not sure if I understand your request. Do you want to enable/disable `longtable`? If so, in the settings, check "Split table in multiple pages". Or do you want an option to use another package instead of `longtable` (such as `supertabular`) ?

**Comment by Warborn123** [comment]
> Hi, I'm not sure if I understand your request. Do you want to enable/disable `longtable`? If so, in the settings, check "Split table in multiple pages". Or do you want an option to use another package instead of `longtable` (such as `supertabular`) ?

Hi, I don’t wish to use the long table, I want to use the original table, as long table has some issues with my document class. Thanks.

**Comment by JDMCreator** [comment]
In the settings, uncheck "Split table in multiple pages".

**Comment by Warborn123** [comment]
> In the settings, uncheck "Split table in multiple pages".

Great, thanks!
