### ISSUE TITLE
unable to import file

### ISSUE THREAD

**Issue by muralikodali** [JDMCreator/LaTeXTableEditor#7]
I am unable to import csv file for conversion.even pasted content is not imported to create table.
opened index.html from local folder.

**Comment by JDMCreator** [comment]
The tool to load files uses WebWorker. The WebWorker technology doesn't work offline with Google Chrome. Try Firefox. I'll add a warning label in the next release.

However, it is strange that you can't use the tool where you paste the content of your csv file. Could you give more details ? What's your browser ? Does it work online ? Can you post the content of your CVS file ?

**Comment by muralikodali** [comment]
A gif file is attached to show the problem
![latextableditor](https://user-images.githubusercontent.com/11482766/43181718-184289c8-8ffc-11e8-9e67-a7c066cc867e.gif)
