### ISSUE TITLE
Auto-Booktabs not working in version 3

### ISSUE THREAD

**Issue by owah** [JDMCreator/LaTeXTableEditor#70]
Hi,

if you use version 3 and draw some `hlines` on your own, the system will decide to use `tblr` for the table, ie:

```
% \usepackage{tabularray}
\begin{table}
\centering
\begin{tblr}{
  hline{2} = {1-2,4}{},
}
 &  &  &  \\
 &  &  &  \\
 &  &  &  \\
 &  &  &  
\end{tblr}
\end{table}
```

If you now enable auto-booktabs and re-generate the LaTeX code, the table won't change, even though the table preview on top does.

**Comment by JDMCreator** [comment]
Bug confirmed.
