### ISSUE TITLE
Advertises blocks toolbar widely

### ISSUE THREAD

**Issue by Oll0w4in** [JDMCreator/LaTeXTableEditor#72]
On newest Chrome version there is an advertise banner that blocks the toolbar widely and makes the site not usable for most.
Reload does not change it and i do not use any addons or something.

![image](https://user-images.githubusercontent.com/29129081/219948246-5e1503e3-46d8-4d61-92bc-2da43d2a2409.png)

**Comment by JDMCreator** [comment]
That is indeed unusable. I will look into it and fix it.

**Comment by HannahKirk** [comment]
I agree that the ads make this tool currently completely unusable -- this is a shame as I really previously liked using latex tables editor.

**Comment by JDMCreator** [comment]
It seems Ezoic has enabled an automatic system to place ads which I have disabled. I have also reduced the number of ads. Let me know if it worked.

**Comment by Oll0w4in** [comment]
@JDMCreator @HannahKirk 
It is now usable again. Thanks for the quick fix. I like using this tool, it is the best in my opinion. Would be a shame to be forced to use an adblocker or another tool, I am fine with ads like this now and like to support this project through ads.

So thanks again, and have a nice day :)
