### ISSUE TITLE
LaTeXTableEditor can't import this table

### ISSUE THREAD

**Issue by alanrunner** [JDMCreator/LaTeXTableEditor#73]
The following math table is not importable.

 \begin{array}{c|ccccc}
      \cdot        & \overline{0} & \overline{1} & \overline{2} & \overline{3} & \overline{4} \\ \hline
      \overline{0} & \overline{0} & \overline{0} & \overline{0} & \overline{0} & \overline{0} \\
      \overline{1} & \overline{0} & \overline{1} & \overline{2} & \overline{3} & \overline{4} \\
      \overline{2} & \overline{0} & \overline{2} & \overline{4} & \overline{1} & \overline{4} \\
      \overline{3} & \overline{0} & \overline{3} & \overline{1} & \overline{4} & \overline{2} \\
      \overline{4} & \overline{0} & \overline{4} & \overline{3} & \overline{2} & \overline{1}
    \end{array}

**Comment by JDMCreator** [comment]
The environment `array` is a matrix and not a table. This editor doesn't support mathematical environments.
