### ISSUE TITLE
Table won't generate.

### ISSUE THREAD

**Issue by U-1SU2U** [JDMCreator/LaTeXTableEditor#76]
<img width="878" alt="image" src="https://github.com/JDMCreator/LaTeXTableEditor/assets/99761659/841a7ef1-ad9b-49e0-a6a2-ecd36e93a4fa">
By clicking the 'Generate' button, nothing is actually generated.
<img width="776" alt="image" src="https://github.com/JDMCreator/LaTeXTableEditor/assets/99761659/71aac475-f9f2-4ae9-b35f-4cfaab975da5">
V3.0, tried reverting to older versions to no avail.

**Comment by JDMCreator** [comment]
Fixed in last version.
