### ISSUE TITLE
Programmatic conversion from html code

### ISSUE THREAD

**Issue by estedeahora** [JDMCreator/LaTeXTableEditor#79]
Hi, 

First of all I want to thank you for the excellent work on _latex-tables_!

I am interested in being able to use _latex-tables_ in an automated way for a set of HTML files containing tables.  

The use case is as follows. From word files (`docx`) with research articles I use Pandoc to generate Markdown files. The idea is to use these _Markdown_ files to get multiple formats (`html`, `tex`->`pdf`, `xml-jats`, `epub`, etc).

The problem is that the tables are not converted correctly. So we are thinking of a parallel process to deal with them. The idea is to convert the tables to html files (from word). Then we can use these files with `html `code for tables, to generate the latex code to achieve a similar output in `pdf`. This code would be "automatically inserted" a posteriori in the markdown depending on the output format that will be used (if the output is html the html code would be copied, if the output is `pdf `the latex code would be copied).

The situation is that we would like to be able to do the conversion from html to latex automatically. Is it possible to use _latex-tables_ through some api or similar? 

Edit: extension of the information. For my use case importing a file containing only the html code of a table gives a good enough result in _latex-tables_. I think the general options (e.g. Latex environment, title, etc) could be given by code in the api call.

**Comment by JDMCreator** [comment]
Hi, as this is a static website, an API is not possible.
