### ISSUE TITLE
Cells with different formatting styles are misgenerated

### ISSUE THREAD

**Issue by CodrinSocol** [JDMCreator/LaTeXTableEditor#80]
I was trying to create a table that had cells with some text bolded and some italic. example: 

ex 1: **Cell 1** _(cell 1)_ 

However, the generated text (using the auto option) generated the italic text bolded as well. the cell outputted:

ex 2: **Cell 1  _(cell 1)_**

To note is that the visual UI showed the correct behaviour (first example above)

- The generated LaTeX code: `\textbf{Cell 1 \textit{(cell 1)}}`
- The expected LaTeX code:  `\textbf{Cell 1} \textit{(cell 1)}`

**Comment by JDMCreator** [comment]
This seems to be happening when generating a `tabularray` environment. In the meantime, under the "Generate" button, you can select "tabular" as the LaTeX environment instead of `auto` or `tabularray`.
