### ISSUE TITLE
copy to clipboard button

### ISSUE THREAD

**Issue by shiva-sunar** [JDMCreator/LaTeXTableEditor#82]
It would be easier to copy the code, if we have the copy to clipboard button.

**Comment by sammaddens** [comment]
Pull request #62 implements this feature, but here is an alternative:

- Add a general copy function in `js.js`.

```javascript
function copyToClipboard(stringText) {
    navigator.clipboard.writeText(stringText);
}
``` 

- Add a copy button in `index.html` (after button `generate-button`).

```html
<button type="button" class="btn btn-success" onclick="copyToClipboard(document.getElementById('c').value);">Copy</button>
```
