### ISSUE TITLE
Generate button for latex does not generate table

### ISSUE THREAD

**Issue by miltoncamacho** [JDMCreator/LaTeXTableEditor#83]
For some reason I am no able to generate a table. I can import the table with no problems but I can't make it generate anything.

**Comment by JDMCreator** [comment]
Hi, using which browser? Are you able to generate the JSON associated with your table? (To do so, click on the `File` menu at the top left, then `Generate JSON`). If so, please paste the JSON here (beware of any confidential or sensitive information in your table, as it will be part of the JSON).

**Comment by miltoncamacho** [comment]
I have tried microsoft edge and firefox and the generate bottom behaves the same. 

Yes, I'm able to generate the JSON.

{
    "options": {
        "gen-comma": false,
        "gen-surround": false,
        "latex-whitespace": false,
        "latex-border": true,
        "latex-command": false,
        "latex-split": true,
        "latex-landscape": false,
        "latex-float": true,
        "fit-table": "sh",
        "latex-hhline": true,
        "latex-hhline-hash": false,
        "latex-tabu": false,
        "latex-color": false,
        "latex-microfix-alignment": false,
        "tex-escape": true,
        "tex-macro": true,
        "html-indent": "tab",
        "html-tbody": false,
        "html-remove-tag": false,
        "csv-separator": ",",
        "bbcode-header": "1",
        "pretext-indent": "two",
        "context-split": false,
        "context-landscape": false,
        "context-float": true,
        "context-indent": "two",
        "wml-indent": "four",
        "latexEnv": "Auto"
    },
    "autoBooktabs": false,
    "caption": {
        "caption": "",
        "numbered": false,
        "label": ""
    },
    "cells": [
        [
            {
                "html": "\n  <b>Study</b>\n  ",
                "rowSpan": 2
            },
            {
                "html": "<b>Name1</b><br>",
                "colSpan": 2
            },
            {
                "html": "\n  <b>Name2</b>\n  ",
                "colSpan": 3
            },
            {
                "html": "\n  <b>Name3</b> <br>&nbsp;\n  "
            },
            {
                "html": "<b>Name4</b>",
                "colSpan": 2
            },
            {
                "html": "\n  <b>Name5</b>\n  ",
                "colSpan": 2
            },
            {
                "html": "\n  <b>Name6</b>\n  ",
                "rowSpan": 2
            },
            {
                "html": "\n  <b>Name7</b>\n  ",
                "rowSpan": 2
            }
        ],
        [
            {
                "html": "<b>asfd</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>adsf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>asdf</b>",
                "css": "background-color: rgb(242, 242, 242);",
                "colSpan": 2
            },
            {
                "html": "<b>adsf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>asdf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>asdf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>asdf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>asdf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "<b>asdf</b>",
                "css": "background-color: rgb(242, 242, 242);"
            }
        ],
        [
            {
                "html": "\n  <b>ASDFG</b><br>\n  "
            },
            {
                "html": "&nbsp; 199 <br>(99.99%)\n  \n\n"
            },
            {
                "html": "&nbsp;299<br>(99)<b></b>\n  "
            },
            {
                "html": "399<br>(99)<b></b>\n  "
            },
            {
                "html": "499<br>(99)<b></b>\n  ",
                "colSpan": 2
            },
            {
                "html": "\n  599<br>(99.99)\n  "
            },
            {
                "html": "\n  699<br>(0.49)\n  "
            },
            {
                "html": "\n  -\n  <br>-<b></b>\n  "
            },
            {
                "html": "\n  799<br>(99)\n  "
            },
            {
                "html": "\n  899<br>(99)\n  "
            },
            {
                "html": "\n  999 <br>(99.99)\n  "
            },
            {
                "html": "1099"
            }
        ],
        [
            {
                "html": "\n  <b>ASDFG</b><br>\n  ",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "&nbsp;199<br>(99.99%)\n  ",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "&nbsp;299<br>(99)",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "399<br>(99)",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "499<br>(99)",
                "css": "background-color: rgb(242, 242, 242);",
                "colSpan": 2
            },
            {
                "html": "599<br>(99.99)<br>",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "699 <br>(0.69)\n  ",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "-",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "799<br>(99)\n  ",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "899<br>(99)",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "999 \n\n<br>(99.99)\n  ",
                "css": "background-color: rgb(242, 242, 242);"
            },
            {
                "html": "1099",
                "css": "background-color: rgb(242, 242, 242);"
            }
        ],
        [
            {
                "html": "<b>ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF ASDF SADF ASDF ASDF ASDF ASDF ASDF ASDF</b>",
                "css": "background-color: rgb(242, 242, 242);",
                "colSpan": 13
            }
        ]
    ],
    "version": "3.0.1"
}
