### ISSUE TITLE
[Request] Option to keep math and commands after import tabularray

### ISSUE THREAD

**Issue by sammaddens** [JDMCreator/LaTeXTableEditor#85]
After importing the following `tabularray` table, two things happen. Math is translated to an internal math mode and the commands are dropped.

```latex
\begin{tblr}{colspec = {Q *{5}{Q[c]}}, hlines, vlines}
$A$ [\si{\square\m}] & 0.20 & 0.50 & 1.00 & 2.00 & 2.50 \\
$p$ [\si{\Pa}] & 12500 & 5000 & 2500 & 1250 & 1000
\end{tblr}
```

![table1](https://github.com/JDMCreator/LaTeXTableEditor/assets/53434469/d1c3640d-3194-404f-b853-db66451ca2cc)

With an option to keep math and commands the result should be the following table. This would be useful for easily modifying existing `tabularray` tables.

![table2](https://github.com/JDMCreator/LaTeXTableEditor/assets/53434469/bd09465d-c9d4-4052-a2dc-76485bc25c75)

**Comment by JDMCreator** [comment]
Will be added to the next release.
