### ISSUE TITLE
The column is frozen. How can we edit it?

### ISSUE THREAD

**Issue by nasauniofadelaide** [JDMCreator/LaTeXTableEditor#89]
**Describe the bug**

**Answer the following questions**
1. Which browser are you using:

**JSON code**

Add the JSON code generated by the editor. To do so, click on "File > Generate JSON" at the top left corner of the editor. It will allow anyone to reproduce the table and any options you selected. Beware of any sensitive or confidential information in your table, as it will be part of the JSON code:

```
Your JSON code here.
```

** Related LaTeX code **

Insert any related LaTeX code here:
```
Your LaTeX code
```

**Comment by JDMCreator** [comment]
>
