### ISSUE TITLE
can not paste values from clipboard

### ISSUE THREAD

**Issue by maltegrosse** [JDMCreator/LaTeXTableEditor#9]
hello, I am using the latest chrome browser and I can not paste any code inside a cell. I imported a latex table - but same issue happens by creating a fresh table

**Comment by maltegrosse** [comment]
I tried to copy paste from a text editor, just for testing the url from the address bar, and i tried from excel. I running windows 10.

**Comment by raphael-sch** [comment]
Pasting shows some weird behaviour. I can paste text from my IDE, the same browser tab, other tabs from the same window. I cannot paste from terminal, another browser window (same browser). I am running Firefox on Ubuntu 16

**Comment by JDMCreator** [comment]
Many people seems to have the same issue, but I can't reproduce it with Chrome or Firefox.

**Comment by jgvinholi** [comment]
I am having the same issue on Microsoft Edge Chromium.

**Comment by JDMCreator** [comment]
I made some great process regarding the paste and undo functions. It should be available in the next release.

**Comment by ShuhuaGao** [comment]
I am having the same issue on Microsoft Edge Chromium.

**Comment by JDMCreator** [comment]
I figured out the issue: plain text could not be pasted, but text with rich text formatting could. A patch will be issued this week.
