### ISSUE TITLE
LaTeX table import fails on commented `%\begin{tabular}`

### ISSUE THREAD

**Issue by gcr** [JDMCreator/LaTeXTableEditor#90]
The editor fails to import LaTeX that contains a commented `\begin` command.

Minimal example:
```latex
\begin{tabular}[ht]
%\begin{tabular}[ht]
a & b & c \\
d & e & f \\
g & g & i
\end{tabular}
```

The following works:
```latex
\begin{tabular}[ht]
a & b & c \\
d & e & f \\
g & g & i
\end{tabular}
```

Thanks for the great product!

**Comment by JDMCreator** [comment]
Confirmed that there's issue with commenting a tabular/table environment. However, your LaTeX is invalid and won't be loaded by the editor.

**Comment by JDMCreator** [comment]
Duplicate of #87
